### ISSUE TITLE
Thanks for this project!

### ISSUE THREAD

**Issue by veeral-patel** [tract-docs/tract#1]
Hi Luc - I just saw your blog post announcing this project on HN.

I'd love to start using it -- but I'm assuming I should wait until the end of 2019, when you release the first version, to do so?

Thanks again!

**Comment by veeral-patel** [comment]
By the way Luc - you seem like you know a lot about Hugo and creating documentation sites!

Are there any Gatsby/Hugo themes you would recommend I check out while I wait for Tract to be ready? I know you mentioned Docsy in your blog post.

Edit: Here's what I've found so far:

https://themes.gohugo.io/hugo-book/
https://github.com/jugglerx/hugo-whisper-theme
https://github.com/doczjs/gatsby-starter-docz
https://github.com/hasura/gatsby-gitbook-starter
https://docusaurus.io/docs/en/site-creation

**Comment by lucperkins** [comment]
@veeral-patel Thank you for the kind words! And yes, I'd recommend waiting a few weeks. I'm still restructuring fundamental things and so this won't be useful to others at the moment. In terms of themes to use now, I'm unfortunately not really familiar with the landscape, but it sounds like you've already found some good options 😄

**Comment by yingw787** [comment]
Hey @lucperkins, chiming in to voice my continued support for hugo-theme-tract :smile: Looking forward to continued development!

**Comment by lucperkins** [comment]
@yingw787 Thank you! Let me know if you have any feature requests!

**Comment by veeral-patel** [comment]
@lucperkins Any idea when Tract will be production-ready? Can't wait to use it.

**Comment by lucperkins** [comment]
@veeral-patel I'd say it's usable now
