### ISSUE TITLE
Setting it up now!

### ISSUE THREAD

**Issue by TomGranot** [tract-docs/tract#11]
Caught wind of your HN post, and am looking for a documentation-like hugo template for a project I'm running. Will post here once it's up and running on Netlify! Thanks for this, btw, looks great.

**Comment by TomGranot** [comment]
Running after [the instructions in the getting started section](https://tract-docs.dev/en/docs/getting-started) of the website yield the following:

```
$ hugo server
Error: add site dependencies: load resources: loading templates: "/home/tom/repos/redcaptom.com/themes/tract/layouts/shortcodes/github-button.html:2:1": parse failed: template: shortcodes/github-button.html:2: function "type" not defined
```

Added a PR in https://github.com/tract-docs/tract/pull/12 to fix this - you were missing a `$`:
https://github.com/tract-docs/tract/pull/12/files#diff-738806b8c1b68cf2875c60ce4c286ba6

Works afterwards!

**Comment by TomGranot** [comment]
So, it's defnitely getting there but I'm hitting submodule problems with deploying to netlify.
Instead of using your version of the repo, I forked it and made some changes. Netlify... does not like that. Not sure why.

Will post some follow ups once I figure out exactly what's wrong.

**Comment by TomGranot** [comment]
Well, cloning the repo as well as submodule-ing it did not work. Ended up cloning then deleting the `.git` folder, and adding the theme directly to my repo. Hacky but works, which is good enough for this project. Anyways - I'm very pleased with the whole experience. Thank you!

**Comment by lucperkins** [comment]
@tomgs Do you have a build step that updates the submodule? The build on tract-docs.dev has this step:

```sh
git submodule foreach git pull origin master
```

**Comment by TomGranot** [comment]
I'm using the exact same setup as you (well, I have - now everything is in the same repo). If I find more issues I'll list them here though, don't worry:)
