### ISSUE TITLE
Migrate to vanilla JS from jQuery

### ISSUE THREAD

**Issue by bbbenji** [tract-docs/tract#2]
Currently, none of the Tract utilized libraries rely on jQuery, and the reasoning for using jQuery is more of an argument for why **not** to use React/Vue/etc:
> I know it’s not cool anymore but I don’t need React.js or Vue or anything crazy like that. Just about everything in Tract is accomplished with plain old HTML and CSS, and jQuery is plenty powerful for the bits that go beyond that.

I would like to petition to rewrite the currently ~45 lines of Jquery in vanilla JS, while the codebase is still small. I would be happy to submit a PR, but don't want to waste time if it won't be merged.

Please consider this request. Otherwise, this project's vision is quite promising.

**Comment by lucperkins** [comment]
@bbbenji I’m not using jQuery yet, but I will be in the coming weeks for some things like search where vanilla JS would be quite cumbersome. But once I've done that I'll ping you to see if you think it can be re-done using vanilla JS.

**Comment by bbbenji** [comment]
Well there is a little jQuery being used. If you feel it will make future development simpler, I can understand. But still would prefer vanilla.

On that note, why not use jQuery from NPM instead of Cloudflare CDN?

**Comment by lucperkins** [comment]
@bbbenji This is a pre-alpha project. I may craft a more sophisticated JS pipeline in the future but for development purposes I'm just doing it the old-fashioned way.

**Comment by bbbenji** [comment]
Looking forward to see where this goes.

**Comment by lucperkins** [comment]
@bbbenji Me too! Thanks a lot for your interest 😄 Page load time is definitely a compelling concern for me, so I will be keeping your suggestion in my thoughts.
