### ISSUE TITLE
New shortcodes

### ISSUE THREAD

**Issue by guumaster** [tract-docs/tract#6]
I'm using this theme for one of my projects and I'm doing some changes and adding shortcodes. You can see the theme used here [guumaster/hostctl](https://guumaster.github.io/hostctl/)

Are you interested on getting PRs with any of that?

Currently my shortcodes are:

### Github buttons
```go
{{<github-button repo="guumaster/hostctl" >}}
{{<github-button repo="guumaster/hostctl" type="fork" >}}
```

The required js can be enable/disable with a site param `githubButton = "true"`

### Asciinema player
```go
{{< asciinema key="your-cast-file" rows="20" cols=100 preload="1" >}}
```

In the case of `asciinema` it only add the required js/css on pages that used the player.

**Comment by lucperkins** [comment]
@guumaster Yes, please do! 😄
